/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import type { Provider } from "@ethersproject/providers";
import type {
  IEscrowFactory,
  IEscrowFactoryInterface,
} from "../../interfaces/IEscrowFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_arbiter",
        type: "address",
      },
      {
        internalType: "address",
        name: "_beneficiary",
        type: "address",
      },
    ],
    name: "createEscrow",
    outputs: [],
    stateMutability: "payable",
    type: "function",
  },
  {
    inputs: [],
    name: "getEscrows",
    outputs: [
      {
        internalType: "address[]",
        name: "",
        type: "address[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_escrow",
        type: "address",
      },
    ],
    name: "removeEscrow",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IEscrowFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IEscrowFactoryInterface {
    return new utils.Interface(_abi) as IEscrowFactoryInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IEscrowFactory {
    return new Contract(address, _abi, signerOrProvider) as IEscrowFactory;
  }
}
